apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: n13-deployment
  labels:
    app: n13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n13
  template:
    metadata:
      labels:
        app: n13
    spec:
      containers:
      - name: n13
        image: gveeden/rcluster:latest
        command: ["/usr/sbin/sshd", "-D"]
        ports:
        - containerPort: 22
      nodeSelector:
        node_type: n13


