apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: n13-deployment
  labels:
    app: n13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n13
  template:
    metadata:
      labels:
        app: n13
    spec:
      containers:
      - name: n13
        image: gveeden/rcluster:latest
        command: ["/usr/sbin/sshd", "-D"]
        ports:
        - containerPort: 22
      nodeSelector:
        node_type: n13
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: n11-deployment
  labels:
    app: n11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n11
  template:
    metadata:
      labels:
        app: n11
    spec:
      containers:
      - name: n11
        image: gveeden/rcluster:latest
        command: ["/usr/sbin/sshd", "-D"]
        ports:
        - containerPort: 22
      nodeSelector:
        node_type: n11
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: n10-deployment
  labels:
    app: n10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n10
  template:
    metadata:
      labels:
        app: n10
    spec:
      containers:
      - name: n10
        image: gveeden/rcluster:latest
        command: ["/usr/sbin/sshd", "-D"]
        ports:
        - containerPort: 22
      nodeSelector:
        node_type: n10
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: n9-deployment
  labels:
    app: n9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n9
  template:
    metadata:
      labels:
        app: n9
    spec:
      containers:
      - name: n9
        image: gveeden/rcluster:latest
        command: ["/usr/sbin/sshd", "-D"]
        ports:
        - containerPort: 22
      nodeSelector:
        node_type: n9
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: n7-deployment
  labels:
    app: n7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n7
  template:
    metadata:
      labels:
        app: n7
    spec:
      containers:
      - name: n7
        image: gveeden/rcluster:latest
        command: ["/usr/sbin/sshd", "-D"]
        ports:
        - containerPort: 22
      nodeSelector:
        node_type: n7
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: n6-deployment
  labels:
    app: n6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n6
  template:
    metadata:
      labels:
        app: n6
    spec:
      containers:
      - name: n6
        image: gveeden/rcluster:latest
        command: ["/usr/sbin/sshd", "-D"]
        ports:
        - containerPort: 22
      nodeSelector:
        node_type: n6
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: n5-deployment
  labels:
    app: n5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n5
  template:
    metadata:
      labels:
        app: n5
    spec:
      containers:
      - name: n5
        image: gveeden/rcluster:latest
        command: ["/usr/sbin/sshd", "-D"]
        ports:
        - containerPort: 22
      nodeSelector:
        node_type: n5
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: n4-deployment
  labels:
    app: n4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n4
  template:
    metadata:
      labels:
        app: n4
    spec:
      containers:
      - name: n4
        image: gveeden/rcluster:latest
        command: ["/usr/sbin/sshd", "-D"]
        ports:
        - containerPort: 22
      nodeSelector:
        node_type: n4
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: n3-deployment
  labels:
    app: n3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n3
  template:
    metadata:
      labels:
        app: n3
    spec:
      containers:
      - name: n3
        image: gveeden/rcluster:latest
        command: ["/usr/sbin/sshd", "-D"]
        ports:
        - containerPort: 22
      nodeSelector:
        node_type: n3
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: n2-deployment
  labels:
    app: n2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n2
  template:
    metadata:
      labels:
        app: n2
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: n2
        image: gveeden/rcluster:latest
        command: ["/usr/sbin/sshd", "-D"]
        ports:
        - containerPort: 22
      nodeSelector:
        node_type: n2
