apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: rcluster-workers
spec:
  template: 
    metadata:
      labels:
        app: rcluster-workers
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: rcluster
        image: gveeden/rcluster
        ports:
        - containerPort: 22
env:
  - name: MY_POD_IP
  valueFrom:
    fieldRef:
      fieldPath: status.podIP