apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: rcluster-workers
spec:
  template: 
    metadata:
      labels:
        app: rcluster-workers
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: rcluster
        image: localhost:5000/gveeden/rcluster
        command: ["/usr/sbin/sshd", "-D"]
        ports:
        - containerPort: 22
