apiVersion: v1
kind: Service
metadata:
  name: worker-service
  labels:
    app: worker
spec:
  ports:
  - port: 80
    name: worker
  clusterIP: None
  selector:
    app: worker
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: r-worker
spec:
  selector:
    matchLabels:
      app: worker
  serviceName: "worker-service"
  replicas: 12
  template: 
    metadata:
      labels:
        app: worker
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "node-role.kubernetes.io/node"
                  operator: Exists
      containers:
      - name: rcluster
        image: localhost:5000/gveeden/rcluster
        command: ["/usr/sbin/sshd", "-D"]
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /root/sharedfs
          name: sharedfs
      volumes:
      - name: sharedfs
        flexVolume:
          driver: rook.io/rook
          fsType: ceph
          options:
            fsName: registryfs
            clusterNamespace: rook
            path: /gveeden
