apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: r-workers
spec:
  template: 
    metadata:
      labels:
        app: r-workers
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "node-role.kubernetes.io/node"
                  operator: Exists
      containers:
      - name: rcluster
        image: localhost:5000/gveeden/rcluster
        command: ["/usr/sbin/sshd", "-D"]
        ports:
        - containerPort: 22
        volumeMounts:
        - mountPath: /root/sharedfs
          name: sharedfs
      volumes:
      - name: sharedfs
        flexVolume:
          driver: rook.io/rook
          fsType: ceph
          options:
            fsName: registryfs
            clusterNamespace: rook
            path: /gveeden
