kill:
	docker kill m1
rm:
	docker rm m1
start:
	docker run --net rclust --ip 172.18.0.10 --name m1 -it gveeden/rcluster:Master
build:
	docker build -t gveeden/rcluster:Master /home/gerald/Dev/rParallel/Master/

